FROM node:18-alpine
RUN npm i -g pnpm@7

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY --chown=node:node . .

CMD ["pnpm", "start:dev"]